In [1]:
import numpy

In [3]:
a = numpy.eyes(3)

AttributeError: module 'numpy' has no attribute 'eyes'

In [4]:
a=numpy.array([1,2,3])

In [5]:
print(a)

[1 2 3]


# Simple Equation

-----

Let us now implement the following equation in Python:

$$ y = x^2$$

where $x = 2$

In [6]:
x=2
y=x*x
print(y)

4


In [8]:
a = numpy.eye(3)

In [9]:
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
